Upgrade pyshark to fix security vulnerability and fix `amqp_code_gen` missing pip dep (#1239)
Summary: Upgrade pyshark to fix security vulnerability and fix
amqp_code_gen missing pip dep

This upgrades the pyshark package to address [this
dependabot](https://github.com/ddelnano/pixie/security/dependabot/4)
vulnerability. When trying to test that the amqp code generation still
works, I noticed that the `dill` dependency is not specified and so our
scripts have been broken on main for some time.

```
$ bazel run //src/stirling/source_connectors/socket_tracer/protocols/amqp/amqp_code_generator:amqp_test_code_gen -- parse_packet

Traceback (most recent call last):
  File "/home/ddelnano/.cache/bazel/_bazel_ddelnano/fa8604ca46879b9b1ffd44d337c531f3/execroot/px/bazel-out/k8-fastbuild/bin/src/stirling/source_connectors/socket_tracer/protocols/amqp/amqp_code_generator/amqp_test_code_gen.runfiles/px/src/stirling/source_connectors/socket_tracer/protocols/amqp/amqp_code_generator/amqp_test_code_gen.py", line 26, in <module>
    import dill
ModuleNotFoundError: No module named 'dill'
```

I was unable to verify that the amqp code generation works fully end to
end because it relies on a amqp pcap file that I can't seem to find. The
amqp pcap files used in stirling's protocol inference code doesn't
include all of the amqp frame types necessary to run the script. I've
created #1238 to follow up with fixing that.

Relevant Issues: N/A

Type of change: /kind bug

Test Plan: Verified that the `dill` dependency fix no longer results in
a missing module error

Signed-off-by: Dom Del Nano <ddelnano@pixielabs.ai>