Migrate the deprecated (v3) download/upload artifact actions to v4 (#2079)
Summary: Migrate the deprecated (v3) download/upload artifact actions to
v4

These are slated for deprecation on Jan 30th, but GitHub is failing
builds already for using these old versions (output copied below).

> Error: This request has been automatically failed because it uses a
deprecated version of `actions/upload-artifact:
0b7f8abb1508181956e8e162db84b466c27e18ce`. Learn more:
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

The breaking changes are described
[here](https://github.com/actions/download-artifact/blob/7fba95161a0924506ed1ae69cdbae8371ee00b3f/docs/MIGRATION.md#migration)
and upon review I don't believe those cases are relevant to our
workflows.

Relevant Issues: N/A

Type of change: /kind cleanup

Test Plan: PR build should succeed. As for others, I was planning to
wait until releases happen

Signed-off-by: Dom Del Nano <ddelnano@gmail.com>
(cherry picked from commit a63b1349c9bcbf714d88eee3c0b4bf2fbc3ec9ee)