Fix cache GetWithPrefix bug
Summary:
Metadata was occasionally crashing because of this issue:
```
fatal error: concurrent map iteration and map write

goroutine 71 [running]:
runtime.throw(0x1d49c4d, 0x26)
        GOROOT/src/runtime/panic.go:774 +0x72 fp=0xc0005cb7f0 sp=0xc0005cb7c0 pc=0x42f6b2
runtime.mapiternext(0xc0005cbb20)
        GOROOT/src/runtime/map.go:858 +0x579 fp=0xc0005cb878 sp=0xc0005cb7f0 pc=0x410d89
pixielabs.ai/pixielabs/src/vizier/services/metadata/controllers/kvstore.(*Cache).GetWithPrefix(0xc00039e340, 0x1d20814, 0x8, 0x2b73e78, 0x0, 0x0, 0x2b73e78, 0x0, 0x0, 0x0, ...)
        src/vizier/services/metadata/controllers/kvstore/cache.go:185 +0x249 fp=0xc0005cbb90 sp=0xc0005cb878 pc=0x1964b19
```
Turns out I forgot to obtain the lock in the GetWithPrefix function, although I remembered it everywhere else.

Test Plan: n/a

Reviewers: zasgar, nserrino, #engineering

Reviewed By: zasgar, #engineering

Differential Revision: https://phab.corp.pixielabs.ai/D3327

GitOrigin-RevId: 464c1c5242d4e279a92680f8575244a7837fb873