fix: add return on err to prevent nil pointer deref panic in goroutine
Summary: If no execScriptClient is returned due to there being an err, the codebase
  still attempts to use the client to call execScriptClient.Recv() shortly thereafter.
  This can result in a runtime panic.

  panic: runtime error: invalid memory address or nil pointer dereference
  [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x47b9342]

  Which appears to be able to bubble up and crash the QB. This patch returns early if
  there is a detected error such that the QB will continue processing.

  Errors where we saw this become an issue are,

  error: connection error: desc = \"transport: Error while dialing dial tcp
  [::1]:50300: connect: connection refused\""

Type of change: /kind fix

Test Plan: Reuse existing unit tests

Signed-off-by: Tim Rupp <caphrim007@gmail.com>