Move mux bpf test helper functions to protocol_checkers for later reuse
Summary: This PR splits out helper functions used in #569 into its own change. The goal is to refactor this code so it can be shared by the existing mux_trace_bpf_test.cc and the new thriftmux_openssl_trace_bpf_test.cc one.

Test Plan:
Verified that the tests that use GetTargetRecords pass (calling code needed to have type specified in certain cases)

I couldn't find a way to add the mux equivalents of ToRecordVector and GetTargetRecords without updating the client code. Omitting that change resulted in the following error.

```
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
src/stirling/source_connectors/socket_tracer/openssl_trace_bpf_test.cc:110:46: error: no matching function for call to 'ToRecordVector'
    std::vector<http::Record> http_records = ToRecordVector(record_batch, server_record_indices);
                                             ^~~~~~~~~~~~~~
./src/stirling/source_connectors/socket_tracer/testing/protocol_checkers.h:41:25: note: candidate template ignored: couldn't infer template argument 'TFrameType'
std::vector<TFrameType> ToRecordVector(const types::ColumnWrapperRecordBatch& rb,
```

Reviewers: #stirling, jps

Reviewed By: #stirling, jps

Subscribers: jps

Signed-off-by: Dom Del Nano <ddelnano@twitter.com>

Differential Revision: https://phab.corp.pixielabs.ai/D12178

GitOrigin-RevId: e3c6c614e7ff37a9c5a7f679dcb34df02bb39c94